"""Update models

Revision ID: 152be2731776
Revises: a990cfe5aaed
Create Date: 2025-02-22 22:59:14.812324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152be2731776'
down_revision: Union[str, None] = 'a990cfe5aaed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cereri_cazare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('camin_preferat', sa.Integer(), nullable=True),
    sa.Column('data_cerere', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['camin_preferat'], ['camine.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['studenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cereri_cazare_id'), 'cereri_cazare', ['id'], unique=False)
    op.create_table('istoric_cazari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('camin_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('taxa_lunara', sa.Integer(), nullable=False),
    sa.Column('status_plata', sa.String(), nullable=False),
    sa.Column('data_cazarii', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camere.id'], ),
    sa.ForeignKeyConstraint(['camin_id'], ['camine.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['studenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_istoric_cazari_id'), 'istoric_cazari', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_istoric_cazari_id'), table_name='istoric_cazari')
    op.drop_table('istoric_cazari')
    op.drop_index(op.f('ix_cereri_cazare_id'), table_name='cereri_cazare')
    op.drop_table('cereri_cazare')
    # ### end Alembic commands ###
