"""Fix ENUM issue

Revision ID: ccdd657ea007
Revises: 
Create Date: 2025-02-22 12:37:46.728764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccdd657ea007'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(), nullable=False),
    sa.Column('adresa', sa.String(), nullable=False),
    sa.Column('capacitate_totala', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camine_id'), 'camine', ['id'], unique=False)
    op.create_table('studenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(), nullable=False),
    sa.Column('prenume', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefon', sa.String(), nullable=False),
    sa.Column('facultate', sa.String(), nullable=False),
    sa.Column('specializare', sa.String(), nullable=False),
    sa.Column('an_studiu', sa.Integer(), nullable=False),
    sa.Column('grupa', sa.String(), nullable=False),
    sa.Column('medie_anuala', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_studenti_id'), 'studenti', ['id'], unique=False)
    op.create_table('camere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camin_id', sa.Integer(), nullable=True),
    sa.Column('numar_camera', sa.String(), nullable=False),
    sa.Column('locuri_disponibile', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camin_id'], ['camine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camere_id'), 'camere', ['id'], unique=False)
    op.create_table('studenti_cazati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('camin_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('taxa_lunara', sa.Float(), nullable=False),
    sa.Column('status_plata', sa.Enum('neplatit', 'platit', 'intarziat', name='status_plata_enum'), nullable=True),
    sa.Column('data_cazare', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camere.id'], ),
    sa.ForeignKeyConstraint(['camin_id'], ['camine.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['studenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studenti_cazati_id'), 'studenti_cazati', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studenti_cazati_id'), table_name='studenti_cazati')
    op.drop_table('studenti_cazati')
    op.drop_index(op.f('ix_camere_id'), table_name='camere')
    op.drop_table('camere')
    op.drop_index(op.f('ix_studenti_id'), table_name='studenti')
    op.drop_table('studenti')
    op.drop_index(op.f('ix_camine_id'), table_name='camine')
    op.drop_table('camine')
    # ### end Alembic commands ###
